### ISSUE TITLE
Histogram label text is stacking (overlay) on every data load interaction

### ISSUE THREAD

**Issue by brethauer** [18F/calc#182] opened 2015-06-22 19:42 UTC
![image](https://cloud.githubusercontent.com/assets/7635133/8291104/500eb0ba-18f5-11e5-96f1-be6ef7cf57e5.png)

**Comment by theresaanna** [comment] 2015-06-22 19:44
Yup, a new label is being created over the old one(s) with each data load. @xtine do you feel like hunting this one down?

**Comment by xtine** [comment] 2015-06-22 19:52
I don't see where the label is being stacked?

**Comment by brethauer** [comment] 2015-06-22 20:00
The x and y axis labels: "Ceiling price (hourly rate)" and "# of results"  

![image](https://cloud.githubusercontent.com/assets/7635133/8291452/b7d7c75c-18f7-11e5-9429-ae57bfd6367c.png)

(also this isn't priority over sprint tasks, just wanted to make sure I captured it)

**Comment by maya** [comment] 2015-06-22 20:00
@brethauer @theresaanna @xtine this is a duplicate of this issue: https://github.com/18F/calc/issues/163

**Closed** 2015-06-24 19:55 UTC
Labels: bug
