### ISSUE TITLE
Stepper looks weird when there are fewer than three steps

### ISSUE THREAD

**Issue by hbillings** [18F/calc#1150] opened 2016-12-21 01:43 UTC
<img width="162" alt="screen shot 2016-12-20 at 5 42 49 pm" src="https://cloud.githubusercontent.com/assets/509309/21374465/d06e44c4-c6db-11e6-92f6-0a8549587a70.png">

**Comment by ericronne** [comment] 2016-12-21 19:04
It was designed for the upload flow; do we need it for a two-step process?

**Comment by jseppi** [comment] 2016-12-21 20:05
Good point. Maybe we can just leave it out of the price list replacement flow. Or, as I suggested in https://github.com/18F/calc/pull/1089#issuecomment-268552860, maybe we should actually have a third "success" step in replacement flow.

**Comment by jseppi** [comment] 2016-12-27 22:33
Closing since we removed the success step in #1089

**Closed by jseppi** 2016-12-27 22:33 UTC
Labels: section: data upload, skill: design
