### ISSUE TITLE
Admin - User list selection links display incorrectly and don't seem to work

### ISSUE THREAD

**Issue by jseppi** [18F/calc#1105] opened 2016-12-12 15:42 UTC
When first loading the list of Users (at `/admin/auth/user/`), the text "All X selected" is visible, even though no users have been selected:

<img width="383" alt="screen shot 2016-12-12 at 9 27 16 am" src="https://cloud.githubusercontent.com/assets/697848/21104755/5a783cdc-c04d-11e6-99ba-a4fa3bd1bb96.png">

After clicking "Select all x users", the "All X selected" text is oddly moved to a different spot on the page, and no users in the list actually appear to be selected:

<img width="732" alt="screen shot 2016-12-12 at 9 32 25 am" src="https://cloud.githubusercontent.com/assets/697848/21105290/4f11341e-c04f-11e6-9114-5b24022f60e1.png">

**Comment by hbillings** [comment] 2016-12-12 23:41
@jseppi I can't reproduce this locally, and `calc-dev` looks like this to me:
<img width="550" alt="screen shot 2016-12-12 at 4 40 05 pm" src="https://cloud.githubusercontent.com/assets/509309/21121458/b2eea248-c089-11e6-81fb-f8efc2972056.png">

I don't see a "Select All Users" option at all, which makes me wonder if I've hidden part of the Django user management UI inadvertently. 😳

**Comment by jseppi** [comment] 2016-12-13 16:01
Huh, so I am also not seeing it on https://calc-dev.app.cloud.gov/admin/auth/user/ but I AM seeing it on https://calc-prod.app.cloud.gov/admin/auth/user/. `calc-prod` actually has DOM elements that are not being shown in `calc-dev`:

<img width="1251" alt="screen shot 2016-12-13 at 10 00 49 am" src="https://cloud.githubusercontent.com/assets/697848/21147562/102c7958-c11b-11e6-9f00-22cf0dcbc92d.png">

I _think_ the difference might be that `calc-prod` has enough users to go over a single page of users, so maybe that is why those extract DOM elements and functionality exist.

**Comment by jseppi** [comment] 2016-12-13 16:08
Yup, that seems to be it. Check out the `actions.html` template here: https://github.com/django/django/blob/3c447b108ac70757001171f7a4791f493880bf5b/django/contrib/admin/templates/admin/actions.html#L7

**Comment by hbillings** [comment] 2016-12-13 16:17
@jseppi ahhh! Thanks; I'll look at that now!

**Comment by hbillings** [comment] 2017-01-05 18:35
Closed by #1109; will be handled more gracefully in #1134.

**Closed by hbillings** 2017-01-05 18:35 UTC
Labels: priority: high, section: site admin, skill: CSS
